[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@solady/=lib/solady/src",
    "@v3-periphery=lib/v3-periphery/contracts"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
